#!/bin/sh
set -e
GIT_ROOT=$(git rev-parse --show-toplevel)
pushd $GIT_ROOT > /dev/null
scspell --use-builtin-base-dict --report-only $(git diff --name-only $(git merge-base --fork-point upstream/develop).. | grep -E "(\.mm|\.h|\.swift)\$")
popd
